### ISSUE TITLE
Modify github-training-camp/lesson-1/lets-start.md

### ISSUE THREAD

**Issue by VedaGao** [JieDing/github-training-camp#2]
Header issue of the document: Data—>Date

https://github.com/JieDing/github-training-camp/blob/main/lesson-1/lets-start.md

**Comment by VedaGao** [comment]
Pls assign this to me. Thanks a lot.

**Comment by JieDing** [comment]
> Pls assign this to me. Thanks a lot.

Thx so much for pointing it out. Plz help me to fix this typo.
